# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "/"
weight = 2

[[main]]
name = "Blog"
url = "/"
weight = 3


  
[[main]]
name = "Contact"
url = ""
weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2


[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 3